# Generated by Django 5.1.6 on 2025-03-22 10:12

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=255)),
                ('site_logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('site_mail', models.EmailField(max_length=254)),
                ('site_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='BD')),
                ('site_address', models.TextField(max_length=200)),
                ('site_bg', models.ImageField(blank=True, null=True, upload_to='sitebg/')),
                ('fb_page', models.URLField(max_length=300)),
                ('linkedIn', models.URLField(max_length=300)),
                ('contact_description', models.TextField(blank=True, max_length=500, null=True)),
                ('fact_title', models.CharField(blank=True, max_length=200, null=True)),
                ('fact_description', models.TextField(blank=True, max_length=500, null=True)),
                ('about_title', models.CharField(max_length=200)),
                ('about_description', models.TextField(max_length=500)),
                ('about_image', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('maintenance_mode', models.BooleanField(default=False)),
            ],
        ),
    ]
