# Generated by Django 5.1.6 on 2025-04-05 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='response',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='messages',
            name='note',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
