# Generated by Django 5.1.6 on 2025-04-05 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_messages_response_alter_messages_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='messages',
            name='response_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='messages',
            name='response',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
